apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: flfwbu9qw-nodejs 
  janus-idp.io/tekton: flfwbu9qw-nodejs
  backstage.io/kubernetes-id: flfwbu9qw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: flfwbu9qw-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  