apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: flfwbu9qw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flfwbu9qw-nodejs 
  name: flfwbu9qw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: flfwbu9qw-nodejs 
